apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpg-mongo-pvc
  namespace: mpg-services
  labels:
    app: mpg-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
