apiVersion: v1
kind: Service
metadata:
  name: mpg-mongo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort}}
  selector:
    app: mpg-mongo
