apiVersion: v1
kind: Service
metadata:
  name: mpg-mongo
  namespace: mpg-services
spec:
  clusterIP: None
  ports:
    - name: mpg-mongo-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: mpg-mongo
